import classNames from '@/utils/classNames';
import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const roboto = Roboto({ 
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ['latin'],
  variable: "--font-roboto"
});

export const metadata: Metadata = {
  title: 'Fun Trek Next',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" data-theme="light" className="transition-all">
      <body className={classNames(
        roboto.variable,
        "container mx-auto px-2 font-roboto"
      )}>
        <div className="flex min-h-screen flex-col justify-between">
          <div>
            <Navbar></Navbar>
            <main className='mt-5'>{children}</main>
          </div>
          <Footer></Footer>
        </div>
        
      </body>
    </html>
  )
}

export default RootLayout;